# Generated by Django 4.1.1 on 2023-01-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_air_line", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="passenger", name="creator",),
    ]
